# Generated by Django 5.2.5 on 2025-08-23 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='area',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Postal code must be 5-6 digits', regex='^\\d{5,6}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
    ]
