# Generated by Django 5.2.5 on 2025-08-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenthistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'appointment histories'},
        ),
    ]
