# Generated by Django 5.2.5 on 2025-08-23 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('locations', '0002_alter_area_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-rating', '-total_reviews']},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unavailability',
            options={'ordering': ['date', 'start_time'], 'verbose_name_plural': 'unavailabilities'},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='locations.area'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
